### ISSUE TITLE
Migrate off of Google Analytics 

### ISSUE THREAD

**Issue by amanahuja** [amanahuja/amanahuja.github.io#3]
I'd like to move away from Google Analytics for web privacy and tracking reasons. 

While I'm aware of alternatives like Matomo, I haven't yet investigated these options. If you are knowledgeable about these things, your input would be welcome.

**Comment by amanahuja** [comment]
My criteria at the moment: 
- no cookies (required)
- privacy forward (required)
- GDPR /CCPA, PERCe...  compliant (required)
- open source (required)
- data portability (required)
- ability to manage at least 3 domains (required)
- features required: basic counter of visits, bounce rate
- features nice-to-have: info about browser, screen size, links followed 

Expected traffic for my purposes is probably like... 100 visits per month. I should be able to find an option that is free or close to free, although I'm happy to pay/donate to support. I don't mind technical work to set things up, I guess, but a hosted solution would be nice so I don't have to worry about maintenance, updates, etc. 

Here are two useful lists

- https://creativerly.com/google-analytics-alternatives/
- https://til.marcuse.info/webmaster/alt-analytics.html
- 

Looking through that list for _hosted_ solutions that have free tiers, then: 
- splitbee 
- beampipe 
- micro-analytics 
- counter.dev 
- Swetrix

**Comment by amanahuja** [comment]
It's apparent that some of my naive "nice to have" features are not privacy-respecting. For example, many of the privacy-forward analytics software track only the landing page and not all the pages loaded. This is better for the user. Thus "top pages" are not available, but "top landing pages" are. 

Cookie-less analytics has limitations, and I'm fine with that. 

counter.dev's documentation states: 
> Counting unique users is achieved with a combination of relying on sessionStorage facilities, the browser's cache mechanism and inspecting the referrer. Using this technique considerably reduces the complexity and load on the server while improving data privacy at the cost of knowing less about users. We can't and don't want to be able to connect single page views to an user identity.

**Comment by louispotok** [comment]
I use self-hosted Matomo on a digital ocean droplet for louispotok.com -- I believe it meets all your criteria except cookies.

[This blog post](https://www.benkuhn.net/analytics/) with a setup for basic server-side analytics may also be useful.

**Comment by amanahuja** [comment]
I've setup Matomo as a new resource on my utility server (pafnuty.com), and I'm testing out the integration. Should be good to go soon.

**Comment by amanahuja** [comment]
I had some problems with the js tracker, but now resolved. For posterity: https://forum.yunohost.org/t/matomo-tracker-redirects-fail/20576/4

Marking this as done.

**Comment by amanahuja** [comment]
Confirmed tracking is working after some months.
